import = ["/home/liamm/.config/alacritty/.alacritty-colorscheme/themes/campbell.toml"]

[font]
size = 14.0
transparent_background_colors = true

[font.italic]
family = "monospace"
style = "Italic"

[window]
opacity = 0.8
"window.decorations_theme_variant" = "none"

[window.padding]
x = 6
y = 6
